### ISSUE TITLE
pip3 installation: /etc/userdocker not created

### ISSUE THREAD

**Issue by saviola777** [joernhees/userdocker#2] opened 2017-11-13 09:59 UTC
When installing userdocker via pip3 (on Arch Linux, if that is relevant), the directory `/etc/userdocker` is not created.

I found the config file in `/usr/lib/python3.6/site-packages/userdocker/config`, created `/etc/userdocker` and copied the `default.py` to `/etc/userdocker/config.py`, which was then correctly picked up.

Not sure if this is an oversight, but either way you could maybe add a note about the location of the config file.

**Comment by joernhees** [comment] 2017-11-13 13:33
hmm, what is your `pip3 --version`?

**Comment by saviola777** [comment] 2017-11-13 13:35
```
pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)
```

**Comment by joernhees** [comment] 2017-11-14 18:18
hmm, I tried to reproduce in a fresh vagrant arch box:

### vagrant box setup
```
vagrant box add archlinux/archlinux
mkdir arch ; cd arch
vagrant init archlinux/archlinux
vagrant up
vagrant ssh
```

### in arch
```
sudo pacman -Sy ; sudo pacman -S python-pip
sudo pip3 install userdocker
ls /etc/userdocker
# shows default.py
pip3 --version
# pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)
```

so can't reproduce :-/

I'll close this by printing a warning in cases no config was found.

If you find a way to reproduce, please reopen.

**Closed as completed** 2017-11-14 18:20 UTC
Labels: enhancement, docs
